[package]
name = "scies-math"
version = "0.2.3"
edition = "2024"
description = "A high-performance, dependency-free mathematical toolkit for Rust. Includes generic matrices, Quaternions, MCMC, ODE/PDE solvers, Time Series, and more."
license = "MIT"
repository = "https://github.com/mytheeramet3dev-x/scies-math"
keywords = ["math", "linear-algebra", "statistics", "numerics", "scientific"]
categories = ["science", "mathematics", "algorithms"]
readme = "README.md"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "matmul"
harness = false

[[bench]]
name = "rng"
harness = false

[[bench]]
name = "ode"
harness = false

[[bench]]
name = "transform"
harness = false

[[bench]]
name = "sampling"
harness = false
