//! Lean 4 and Mathlib4 theorem export bridge.

use crate::symbolic::Expr;

/// Converts a symbolic expression [`Expr`] into standard Lean 4 syntax.
pub fn expr_to_lean(expr: &Expr) -> String {
    match expr {
        Expr::Integer(n) => format!("{n}"),
        Expr::Rational(r) => format!("({} / {})", r.numer(), r.denom()),
        Expr::Symbol(s) => s.clone(),
        Expr::Add(terms) => {
            let inner: Vec<String> = terms.iter().map(expr_to_lean).collect();
            format!("({})", inner.join(" + "))
        }
        Expr::Mul(factors) => {
            let inner: Vec<String> = factors.iter().map(expr_to_lean).collect();
            format!("({})", inner.join(" * "))
        }
        Expr::Pow(b, e) => format!("({} ^ {})", expr_to_lean(b), expr_to_lean(e)),
        Expr::Neg(inner) => format!("(-{})", expr_to_lean(inner)),
        Expr::Sin(inner) => format!("(Real.sin {})", expr_to_lean(inner)),
        Expr::Cos(inner) => format!("(Real.cos {})", expr_to_lean(inner)),
        Expr::Exp(inner) => format!("(Real.exp {})", expr_to_lean(inner)),
        Expr::Ln(inner) => format!("(Real.log {})", expr_to_lean(inner)),
        Expr::Sqrt(inner) => format!("(Real.sqrt {})", expr_to_lean(inner)),
    }
}

/// Generates a Lean 4 theorem declaration skeleton with provenance metadata and Mathlib imports.
///
/// # Notice
/// The generated text represents an unverified theorem skeleton. A mathematical proof
/// is only established once processed and accepted by the Lean 4 proof checker.
pub fn export_lean4_theorem(
    theorem_name: &str,
    hypotheses: &[(&str, &str)],
    conclusion: &str,
    proof_tactic: Option<&str>,
) -> String {
    let mut out = String::new();
    out.push_str("/-!\n");
    out.push_str("  Generated by scies-math-th (v0.3.0)\n");
    out.push_str("  Status: Generated theorem skeleton (requires verification by Lean 4 kernel)\n");
    out.push_str("-/\n\n");
    out.push_str("import Mathlib\n\n");
    out.push_str(&format!("theorem {theorem_name}"));

    if !hypotheses.is_empty() {
        for (var_name, var_type) in hypotheses {
            out.push_str(&format!(" ({var_name} : {var_type})"));
        }
    }

    out.push_str(&format!(" : {conclusion} := by\n"));
    let tactic = proof_tactic.unwrap_or("sorry");
    for line in tactic.lines() {
        out.push_str(&format!("  {line}\n"));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lean_export() {
        let x = Expr::sym("x");
        let expr = Expr::Add(vec![
            Expr::Pow(Box::new(x.clone()), Box::new(Expr::int(2))),
            Expr::int(1),
        ]);

        let lean_str = expr_to_lean(&expr);
        assert!(lean_str.contains("(x ^ 2)"));

        let thm = export_lean4_theorem(
            "quadratic_positive",
            &[("x", "ℝ")],
            "x ^ 2 + 1 > 0",
            Some("positivity"),
        );
        assert!(thm.contains("theorem quadratic_positive (x : ℝ) : x ^ 2 + 1 > 0 := by"));
        assert!(thm.contains("positivity"));
    }
}
